### ISSUE TITLE
Could not build EFC data due to AssertionError when building system.img

### ISSUE THREAD

**Issue by Umeaboy** [sonyxperiadev/device-sony-maple#60]
I just tried to build 8.1.0_r52 and this is the end result from building the system.img:

++++ system ++++

creating system.img...
Running:  build_verity_tree -s 7707033600
60686336
Running:  system/extras/verity/build_verity_metadata.py size 7707033600
32768
Running:  fec -s 7767752704
61411328
Running:  build_verity_tree -s 7645966336
60207104
Running:  system/extras/verity/build_verity_metadata.py size 7645966336
32768
Running:  fec -s 7706206208
60928000
Running:  build_verity_tree -s 7615434752
59969536
Running:  system/extras/verity/build_verity_metadata.py size 7615434752
32768
Running:  fec -s 7675437056
60682240
Running:  build_verity_tree -s 7600168960
59850752
Running:  system/extras/verity/build_verity_metadata.py size 7600168960
32768
Running:  fec -s 7660052480
60559360
Running:  build_verity_tree -s 7592534016
59789312
Running:  system/extras/verity/build_verity_metadata.py size 7592534016
32768
Running:  fec -s 7652356096
60502016
Running:  build_verity_tree -s 7588716544
59760640
Running:  system/extras/verity/build_verity_metadata.py size 7588716544
32768
Running:  fec -s 7648509952
60469248
Running:  build_verity_tree -s 7586807808
59744256
Running:  system/extras/verity/build_verity_metadata.py size 7586807808
32768
Running:  fec -s 7646584832
60452864
Running:  build_verity_tree -s 7585853440
59736064
Running:  system/extras/verity/build_verity_metadata.py size 7585853440
32768
Running:  fec -s 7645622272
60444672
Running:  build_verity_tree -s 7586332672
59740160
Running:  system/extras/verity/build_verity_metadata.py size 7586332672
32768
Running:  fec -s 7646105600
60452864
Running:  build_verity_tree -s 7586570240
59744256
Running:  system/extras/verity/build_verity_metadata.py size 7586570240
32768
Running:  fec -s 7646347264
60452864
Running:  build_verity_tree -s 7586689024
59744256
Running:  system/extras/verity/build_verity_metadata.py size 7586689024
32768
Running:  fec -s 7646466048
60452864
Running:  build_verity_tree -s 7586750464
59744256
Running:  system/extras/verity/build_verity_metadata.py size 7586750464
32768
Running:  fec -s 7646527488
60452864
Running:  build_verity_tree -s 7586779136
59744256
Running:  system/extras/verity/build_verity_metadata.py size 7586779136
32768
Running:  fec -s 7646556160
60452864
Running:  build_verity_tree -s 7586795520
59744256
Running:  system/extras/verity/build_verity_metadata.py size 7586795520
32768
Running:  fec -s 7646572544
60452864
Running:  build_verity_tree -s 7586803712
59744256
Running:  system/extras/verity/build_verity_metadata.py size 7586803712
32768
Running:  fec -s 7646580736
60452864
Running:  mkuserimg_mke2fs.sh -s /tmp/tmpXtm_lk/system /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/IMAGES/system.img ext4 system 7586803712 -T 1230764400 -C /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/META/filesystem_config.txt -B /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/IMAGES/system.map -L system -U 85963ee9-56f1-5793-aec4-671ba1607723 -S 35d8cf98-2bcf-5f77-9016-b3df14a5f955 out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/META/file_contexts.bin
MKE2FS_CONFIG=./system/extras/ext4_utils/mke2fs.conf E2FSPROGS_FAKE_TIME=1230764400 mke2fs -L system -U 85963ee9-56f1-5793-aec4-671ba1607723 -E android_sparse,hash_seed=35d8cf98-2bcf-5f77-9016-b3df14a5f955 -t ext4 -b 4096 /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/IMAGES/system.img 1852247
mke2fs 1.43.3 (04-Sep-2016)
Creating filesystem with 1852247 4k blocks and 463296 inodes
Filesystem UUID: 85963ee9-56f1-5793-aec4-671ba1607723
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information: done 

E2FSPROGS_FAKE_TIME=1230764400 e2fsdroid -T 1230764400 -C /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/META/filesystem_config.txt -B /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/IMAGES/system.map -S out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/META/file_contexts.bin -f /tmp/tmpXtm_lk/system -a /system /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/IMAGES/system.img
loaded 2785 fs_config entries
Created filesystem with 2795/463296 inodes and 289690/1852247 blocks
Running:  build_verity_tree -A aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7 /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/IMAGES/system.img /tmp/tmpay7vAy_verity_images/verity.img
842da46a0cfc4eb5cc82b0e731704b3f59c2ac6cf4b2a67da1cbc5f7595d8208 aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7
Running:  system/extras/verity/build_verity_metadata.py build 7586803712 /tmp/tmpay7vAy_verity_images/verity_metadata.img 842da46a0cfc4eb5cc82b0e731704b3f59c2ac6cf4b2a67da1cbc5f7595d8208 aee087a5be3b982978c923f566a94613496b417f2af592639bc80d141e34dfe7 /dev/block/platform/soc/1da4000.ufshc/by-name/system verity_signer build/target/product/security/verity.pk8
['verity_signer', '/tmp/tmpNfIOXs.table', 'build/target/product/security/verity.pk8', '/tmp/tmpkj7Qwf.sig']
appending /tmp/tmpay7vAy_verity_images/verity_metadata.img to /tmp/tmpay7vAy_verity_images/verity.img
Running:  fec -e -p 0 /home/kristoffer/android/out/target/product/maple/obj/PACKAGING/target_files_intermediates/aosp_g8142-target_files-eng.kristoffer/IMAGES/system.img /tmp/tmpay7vAy_verity_images/verity.img /tmp/tmpay7vAy_verity_images/verity_fec.img
terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Could not build FEC data! Error: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc

Traceback (most recent call last):
  File "./build/tools/releasetools/add_img_to_target_files", line 776, in <module>
    main(sys.argv[1:])
  File "./build/tools/releasetools/add_img_to_target_files", line 770, in main
    AddImagesToTargetFiles(args[0])
  File "./build/tools/releasetools/add_img_to_target_files", line 614, in AddImagesToTargetFiles
    output_zip, recovery_img=recovery_image, boot_img=boot_image)
  File "./build/tools/releasetools/add_img_to_target_files", line 145, in AddSystem
    block_list=block_list)
  File "./build/tools/releasetools/add_img_to_target_files", line 277, in CreateImage
    assert succ, "build " + what + ".img image failed"
AssertionError: build system.img image failed
ninja: build stopped: subcommand failed.
03:37:07 ninja failed with: exit status 1

I'm fully synced and all patches was successfully applied.

**Comment by Umeaboy** [comment]
I ran source build/envsetup.sh && lunch and choose number 52 and then make otapackage.

**Comment by Umeaboy** [comment]
Ping!

**Comment by jerpelea** [comment]
what Linux are you using?

**Comment by Umeaboy** [comment]
Mageia 6. I have been able to build before without this error.

**Comment by Umeaboy** [comment]
Any more info needed?

**Comment by jamuir** [comment]
I have hit failures building FEC data due to running out of disk space.

Did you confirm that you have enough disk?

Note that sony-open-devices issues should be logged here:

https://github.com/sonyxperiadev/bug_tracker/issues
